cas:
  authn:
    oidc:
      issuer: https://localhost:8443/cas/oidc
  server:
    name: https://localhost:8443
    prefix: ${cas.server.name}/cas
  serviceRegistry:
    initFromJson: false
    json:
      location: classpath:/myservices

# Allow cors request for implicit flow
# i.e.: https://cas-server/cas/oidc/.well-known/openid-configuration
  httpWebRequest:
    cors:
      enabled: true
      allowOrigins:
        - "*"
  logout:
    followServiceRedirects: true
    redirectParameter: service
